name: Build Satella Rootless

on:
  push:
    branches: [ emt, main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Clean and Install Theos and SDKs
      run: |
        # حذف أي بقايا مجلدات قديمة لمنع التعارض 128
        rm -rf ${{ github.workspace }}/theos
        
        # تحميل أداة ثيوس بشكل نظيف وكامل
        git clone --recursive https://github.com ${{ github.workspace }}/theos
        
        # تحميل الـ SDKs داخل المجلد الصحيح بعد تحميل ثيوس
        git clone --depth=1 https://github.com ${{ github.workspace }}/theos/sdks

    - name: Compile Package
      env:
        THEOS: ${{ github.workspace }}/theos
        THEOS_PACKAGE_SCHEME: rootless
      run: |
        make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Satella-Arabic-Rootless
        path: packages/*.deb
