name: Build Satella Rootless

on:
  push:
    branches: [ emt, main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Theos and SDKs
      run: |
        brew install ldid xz
        bash -c "$(curl -fsSL https://githubusercontent.com)"
        mv $HOME/theos $GITHUB_WORKSPACE/theos-system
        cd $GITHUB_WORKSPACE/theos-system
        make update-sdks

    - name: Compile Package
      run: |
        export THEOS=$GITHUB_WORKSPACE/theos-system
        make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless TARGET=iphone:clang:latest:14.0
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Satella-Arabic-Rootless
        path: packages/*.deb
