name: Build Satella Rootless

on:
  push:
    branches: [ emt, main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Theos Environment
      uses: answersandcode/setup-theos@v1.1

    - name: Compile Package
      run: |
        make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless TARGET=iphone:clang:latest:14.0
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Satella-Arabic-Rootless
        path: packages/*.deb
